### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by pietru2004** [totaljs/cmsbundle#1]
I'm sorry but could there be added option for using other databases? Like MariaDB or MongoDB?

**Comment by petersirka** [comment]
Hi @pietru2004, not possible. You can use MariaDB or MongoDB for other things, but the core of CMS must use its DB engine.

**Comment by pietru2004** [comment]
So there is no option to add it for saving website pages? I mean I have scalability concerns.

**Comment by pietru2004** [comment]
I seen Total JS has something called DBMS

So that is why I ask

**Comment by petersirka** [comment]
**So there is no option to add it for saving website pages?**
Yes. CMS can't be provided in the cluster, but it can handle around/max 1000 per seconds.

DBMS is an additional module for working with other databases. But CMS has exact internal functionality.

**Comment by pietru2004** [comment]
I hope that there will be such option(could be as a secondary storage option) in future as it seams bit dangerous to have website in one place without easy scalability. With docker it would be possible to run many instances pointing to one save location but I guess they would not update status/database data until restart...

**Comment by petersirka** [comment]
It's not dangerous. Total.js CMS is a tiny app with great functionality that will work independently and without any 3rd party dependencies.

**Comment by pietru2004** [comment]
so I can just scale it with referencing all instances to one storage place? ex. binded Samba instance.

**Comment by petersirka** [comment]
Theoretically yes. But the CMS app is not optimized for the cluster. It's tiny app.

**Comment by pietru2004** [comment]
Tiny but from what I seen it is powerfull, I would love to see it ability to use other databases like MariaDB and MongoDB, so I guess it could be goal for future especially seeing that total has DBMS(it could be optional dependancy for CMS app).
Almost all cms software I have seen was missing feautures I needed:
cards, per page tabs and in some cases file downloads, 
and even if it would be possible to do it with them they always made Blog as basic template with little guide how to make other types of websites.
But I see it as out of the box for Total CMS basicaly all I need is to download some widgets and that's it
